---
name: ublue-cosmic
description: This is my personal OS image.

#Base Image
base-image: ghcr.io/ublue-os/base-main
image-version: 44

#Module Configuration, Executed in Order
modules:
  - type: script
    #Run Scripts
    scripts:
      - kernel-cachyos.sh
      - cosmic.sh

  - type: dnf
    #Install Packages
    install:
      packages:
        - fastfetch
        - fish
    
    #Remove Packages
    remove:
      packages:
        - firefox-langpacks
        - firefox
        - nvtop
        - htop

  - type: systemd
    system:
      #Enable services
      enabled:
        - cosmic-greeter

  #This sets up the proper policy & signing files for signed images to work fully
  - type: signing
