---
name: ublue-cosmic
description: This is my personal OS image.

#Base Image
base-image: ghcr.io/ublue-os/base-main
image-version: latest

#Module Configuration, Executed in Order
modules:
  - type: script
    scripts:
      - kernel-cachyos.sh

  - type: dnf
    #Install Packages
    group-install:
      with-optional: false
      install-weak-deps: false
      packages:
        - cosmic-desktop
      exclude:
        - system-config-printer
        - gnome-keyring-pam
    install:
      packages:
        - fastfetch
        - fish
        - btop
    
    #Remove Packages
    remove:
      packages:
        - firefox-langpacks
        - firefox
        - nvtop
        - htop

  #This sets up the proper policy & signing files for signed images to work fully
  - type: signing
